
########################################
# Services
########################################

services:

  neo4j:
    image: neo4j:latest
    volumes:
        - $PWD/docker.neo4j/neo4j/logs:/logs
        - $PWD/docker.neo4j/neo4j/config:/config
        - $PWD/docker.neo4j/neo4j/data:/data
        - $PWD/docker.neo4j/neo4j/plugins:/plugins
    environment:
        #- NEO4J_AUTH_FILE=/run/secrets/neo4j_auth_file
        - NEO4J_AUTH=neo4j/your_password
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: no
    secrets:
      - neo4j_auth_file

  ########################################

  cypher:
    image: cyphergui:latest
    build:
      context: ./docker.cyphergui
      dockerfile: ./Dockerfile
    volumes:
      - $PWD/docker.cyphergui/cypher:/var/cypher
    environment:
        - VAR=value
    ports:
      - "3010:1234"
    restart: no
    depends_on:
      - neo4j
    secrets:
      - neo4j_auth_file

  ########################################
 
  neo4j-mcp:
    image: mcp/neo4j-memory:latest
    ports:
      - "8010:8000"
    environment:
      - NEO4J_URI="bolt://host.docker.internal:7687"
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=your_password
      - NEO4J_DATABASE=neo4j
      - NEO4J_TRANSPORT=http
      - NEO4J_MCP_SERVER_HOST=0.0.0.0
      - NEO4J_MCP_SERVER_PORT=8000
      - NEO4J_MCP_SERVER_PATH=/mcp/
    depends_on:
      - neo4j

########################################

# Secrets
########################################

secrets:
  neo4j_auth_file:
    file: docker.neo4j/.secrets/neo4j_auth_file

